### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Dreamsorcerer** [jsfehler/flake8-multiline-containers#19]
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 331, in run
    self.run_serial()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 315, in run_serial
    checker.run_checks()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8_multiline_containers.py", line 286, in run
    self.check_for_js102(index, line)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8_multiline_containers.py", line 228, in check_for_js102
    self._check_closing('(', ')', line_number, line, ErrorCodes.JS102)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8_multiline_containers.py", line 200, in _check_closing
    if index != self.last_starts_at[-1]:
IndexError: list index out of range
```

Fails on this snippet:
```
a().b(a,
      b)
```

**Comment by PeterJCLaw** [comment]
Hrm, I get a similar error, though I can't reproduce it with that code example.

For me, the trigger code is this:
``` python
func(
    (
        "long string such that we use parens"
    ),
)
```

**Comment by PeterJCLaw** [comment]
Unfortunately my snippet only reproduces when that snippet is on its own in a file.

**Comment by PeterJCLaw** [comment]
Ah, turns out that this snippet passes:
``` python
x = """
"""

func(
    (
        "long string such that we use parens"
    ),
)
```
even though this also errors:
``` python
"""
"""

func(
    (
        "long string such that we use parens"
    ),
)
```
So presumably there's something about it being a multi-line string?
