### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Dreamsorcerer** [jsfehler/flake8-multiline-containers#5]
When running on a project I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 382, in _run
    self.run_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 301, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 330, in run
    self.run_serial()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 314, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 608, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 504, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.7/site-packages/flake8_multiline_containers.py", line 227, in run
    self.check_for_js102(index, line)
  File "/usr/local/lib/python3.7/site-packages/flake8_multiline_containers.py", line 168, in check_for_js102
    self._check_closing('{', '}', line_number, line, ErrorCodes.JS102)
  File "/usr/local/lib/python3.7/site-packages/flake8_multiline_containers.py", line 144, in _check_closing
    if index != self.last_starts_at[-1]:
IndexError: list index out of range

flake8.processor          MainProcess  14842 WARNING  Plugin requested optional parameter "last_starts_at" but this is not an available parameter.
```

**Comment by jsfehler** [comment]
@Dreamsorcerer Are you using v0.0.4? If so, are you getting this error on anything/everything, or can you isolate?

**Comment by Dreamsorcerer** [comment]
I believe so, I just pip installed it as normal, about a week ago. I'll try running it again when I'm at work, and see if I can figure out which file caused it.

**Comment by Dreamsorcerer** [comment]
This code throws the error:

```
a = {
    a: '{f}'.format(f=b) for c in d}
```

**Comment by jsfehler** [comment]
@Dreamsorcerer Should be fixed in v0.0.5

**Comment by Dreamsorcerer** [comment]
Unfortunately, that reaches another issue in another file with nested dicts.
```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 382, in _run
    self.run_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 301, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 330, in run
    self.run_serial()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 314, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 608, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 504, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.7/site-packages/flake8_multiline_containers.py", line 250, in run
    self.check_for_js102(index, line)
  File "/usr/local/lib/python3.7/site-packages/flake8_multiline_containers.py", line 191, in check_for_js102
    self._check_closing('{', '}', line_number, line, ErrorCodes.JS102)
  File "/usr/local/lib/python3.7/site-packages/flake8_multiline_containers.py", line 164, in _check_closing
    index = self._get_closing_index(line, close_character)
  File "/usr/local/lib/python3.7/site-packages/flake8_multiline_containers.py", line 132, in _get_closing_index
    if line[s] == close_character:
IndexError: string index out of range
```

Error thrown with this code:
```
{
    'a': {}
}
```

**Comment by jsfehler** [comment]
I'm not getting any errors with that block. Is there a larger piece around it?

**Comment by Dreamsorcerer** [comment]
No, I trimmed the file down to exactly that. Can you try saving it without a trailing newline at the end of the file (I think it might be related to being the last line of the file)? If not, I'll upload a file with the example.

**Comment by Dreamsorcerer** [comment]
Yeah, it's only occurring when `}` is the last character of the file (so no trailing newline), while also being on it's own line.
[test.txt](https://github.com/jsfehler/flake8-multiline-containers/files/3405895/test.txt)

**Comment by Dreamsorcerer** [comment]
So, I think that issue can be fixed by prepending `-1` to the slices list on line 128.

I've found another error though, from multiple opening braces on one line and close braces on multiple lines:
```
{'a': {
    'b': 1}
}
```

**Comment by jsfehler** [comment]
Both issues are fixed on master. I'll make a release this weekend.

```
{'a': {
    'b': 1}
}
```
This now triggers JS101 and JS102.

```
{'a': {
    'b': 1
}
}
```
This only triggers JS101. It's still wrong, but I don't see the point trying to predict where the closing character of the inner container should be.

**Comment by Dreamsorcerer** [comment]
As long as the issue is highlighted without throwing an exception, developers will know the correct position for the character.

Successfully ran flake8 on our full project, so problem sorted now, thanks.
